export const EXERCISES = [
  { name: 'Leg Press', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'Hack Squat', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'Smith Machine Squat', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'Smith Machine Bench Press', category: 'Strength', muscle: 'Chest', type: 'Machine' },
  { name: 'Smith Machine Incline Press', category: 'Strength', muscle: 'Chest', type: 'Machine' },
  { name: 'Seated Chest Press', category: 'Strength', muscle: 'Chest', type: 'Machine' },
  { name: 'Incline Chest Press', category: 'Strength', muscle: 'Chest', type: 'Machine' },
  { name: 'Pec Deck', category: 'Strength', muscle: 'Chest', type: 'Machine' },
  { name: 'Cable Fly', category: 'Strength', muscle: 'Chest', type: 'Cable' },
  { name: 'Lat Pulldown', category: 'Strength', muscle: 'Back', type: 'Machine' },
  { name: 'Seated Row', category: 'Strength', muscle: 'Back', type: 'Machine' },
  { name: 'Chest Supported Row', category: 'Strength', muscle: 'Back', type: 'Machine' },
  { name: 'Assisted Pull-Up', category: 'Strength', muscle: 'Back', type: 'Machine' },
  { name: 'Straight Arm Pulldown', category: 'Strength', muscle: 'Back', type: 'Cable' },
  { name: 'Shoulder Press Machine', category: 'Strength', muscle: 'Shoulders', type: 'Machine' },
  { name: 'Lateral Raise Machine', category: 'Strength', muscle: 'Shoulders', type: 'Machine' },
  { name: 'Rear Delt Fly Machine', category: 'Strength', muscle: 'Shoulders', type: 'Machine' },
  { name: 'Cable Lateral Raise', category: 'Strength', muscle: 'Shoulders', type: 'Cable' },
  { name: 'Biceps Curl Machine', category: 'Strength', muscle: 'Arms', type: 'Machine' },
  { name: 'Preacher Curl Machine', category: 'Strength', muscle: 'Arms', type: 'Machine' },
  { name: 'Cable Curl', category: 'Strength', muscle: 'Arms', type: 'Cable' },
  { name: 'Triceps Pushdown', category: 'Strength', muscle: 'Arms', type: 'Cable' },
  { name: 'Dip Machine', category: 'Strength', muscle: 'Arms', type: 'Machine' },
  { name: 'Triceps Extension Machine', category: 'Strength', muscle: 'Arms', type: 'Machine' },
  { name: 'Seated Leg Curl', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'Lying Leg Curl', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'Leg Extension', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'Hip Abductor', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'Hip Adductor', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'Glute Drive Machine', category: 'Strength', muscle: 'Glutes', type: 'Machine' },
  { name: 'Cable Kickback', category: 'Strength', muscle: 'Glutes', type: 'Cable' },
  { name: 'Standing Calf Raise', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'Seated Calf Raise', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'Ab Crunch Machine', category: 'Strength', muscle: 'Core', type: 'Machine' },
  { name: 'Torso Rotation Machine', category: 'Strength', muscle: 'Core', type: 'Machine' },
  { name: 'Cable Crunch', category: 'Strength', muscle: 'Core', type: 'Cable' },
  { name: 'Back Extension Machine', category: 'Strength', muscle: 'Back', type: 'Machine' },
  { name: 'Hip Thrust Machine', category: 'Strength', muscle: 'Glutes', type: 'Machine' },
  { name: 'Pendulum Squat', category: 'Strength', muscle: 'Legs', type: 'Machine' },
  { name: 'T-Bar Row Machine', category: 'Strength', muscle: 'Back', type: 'Machine' },
  { name: 'Treadmill', category: 'Cardio', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Swimming', category: 'Cardio', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Elliptical', category: 'Cardio', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Stair Climber', category: 'Cardio', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Rowing Machine', category: 'Cardio', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Recumbent Bike', category: 'Cardio', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Upright Bike', category: 'Cardio', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Arc Trainer', category: 'Cardio', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Ski Erg', category: 'Cardio', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Assault Bike', category: 'Cardio', muscle: 'Cardio', type: 'Cardio' },
]

export const MOVIE_QUOTES = [
  'It’s what you do right now that makes a difference. — Black Hawk Down',
  'Why do we fall? So we can learn to pick ourselves up. — Batman Begins',
  'Just keep swimming. — Finding Nemo',
  'Do, or do not. There is no try. — The Empire Strikes Back',
  'Great men are not born great, they grow great. — The Godfather',
]

export const STARTER_STEPS = [
  'Tap Build today’s workout.',
  'Tap + on anything you want in the plan.',
  'Start the workout once the plan looks right.',
  'Open one exercise card at a time to log sets.',
]

export const DEFAULT_SETTINGS = {
  smartMode: true,
  weightUnit: 'lbs',
  distanceUnit: 'mi',
  darkMode: false,
  colorCoding: true,
}
